function ajouter_un_member() {
    var eq = document.createElement('div');
    eq.innerHTML = '<div style="color:white;font-family:monospace;font-size:22px;"><h3>new member</h3></div><div id="add" name="add2"><div class="main-flex-w3ls-sectns"><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="Name" placeholder="Nom et Prénom du Porteur" required=""></div><div class="radio-section"><label>Civilité</label><ul class="radio-buttons-w3-agileits"><li><input type="radio" id="a-option" name="selector1"><label for="a-option">Mr</label><div class="check"></div></li><li><input type="radio" id="b-option" name="selector1"><label for="b-option">MMe</label><div class="check"><div class="inside"></div></div></li></ul><div class="clear"></div></div></div><div class="main-flex-w3ls-sectns"><div class="field-agileinfo-spc form-w3-agile-text1"><input type="Email" name="email" placeholder="Email" required=""></div><div class="field-agileinfo-spc form-w3-agile-text2"><input type="text" name="Phone no" placeholder="Tel" required=""></div></div><div class="field-agileinfo-spc form-w3-agile-text"><input type="text" name="structure de recherche" placeholder="Structure de recherche" required=""></div><div class="main-flex-w3ls-sectns"><div class="field-agileinfo-spc form-w3-agile-text1"><select class="form-control"><option>Grade</option><option value="1">PES</option><option value="2">PH</option><option value="3">PA</option></select></div><div class="field-agileinfo-spc form-w3-agile-text2"><select class="form-control"><option>Spécialité</option><option value="Architecture">Architecture</option><option value="Biochimie">Biochimie</option><option value="Biologie moléculaire">Biologie moléculaire</option><option value="Dentisterie">Dentisterie</option><option value="Génie Chimique">Génie Chimique</option><option value="Génétique">Génétique</option><option value="Immunologie">Immunologie</option><option value="Informatique">Informatique</option><option value="Lettres">Lettres</option><option value="Mathématiques">Mathématiques</option><option value="Microbiologie">Microbiologie</option><option value="Médecine">Médecine</option></select></div></div><div class="field-agileinfo-spc form-w3-agile-text"><textarea name="tache" placeholder="Tâches à réaliser dans le projet"></textarea></div></div>'
    document.getElementById('addeq').appendChild(eq);

};

function ajouter_une_pub() {
    var eq = document.createElement('div');
    eq.innerHTML = '<h4 class="sub-heading-agileits">Ajouter une nouvelle publication</h4><div class="field-agileinfo-spc form-w3-agile-text1"><input id="inf" type="text" name="titreComplet" value="" placeholder="Titre Complet de la publication"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="inf" type="text" name="auteurs" value="" placeholder="Auteurs"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="inf" type="text" name="perioSC" value="" placeholder="Nom complet du périodique scientifique"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="inf" type="text" name="vipa" value="" placeholder="Volume, issus, pages et année"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="inf" type="text" name="theme" value="" placeholder="Thématique"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="inf" type="text" name="lien" value="" placeholder="Lien web"></div>'
    document.getElementById('pub_ajoute').appendChild(eq);
};

function ajouter_une_comm() {
    var eq = document.createElement('div');
    eq.innerHTML = '<h4 class="sub-heading-agileits">Ajouter une nouvelle communication</h4><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="communication" value="" placeholder="Titre Complet de la communication"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="auteurs" value="" placeholder="Auteurs"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="perioSC" value="" placeholder="Nom complet de la rencontre scientifique"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="lieu" value="" placeholder="Lieu d organisation"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="datepicker1" name="Text" type="text" placeholder="Date de la rencontre" value="" onfocus="this.value = "";" onblur="if (this.value == "") {this.value = "mm/dd/yyyy";}" required=""></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="theme" value="" placeholder="Thématique"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="lien" value="" placeholder="Lien web"></div>'
    document.getElementById('ajouter_une_comm').appendChild(eq);
}

function ajouter_une_these() {
    var eq = document.createElement('div');
    eq.innerHTML = '<h4 class="sub-heading-agileits">Ajouter une nouvelle thèse soutenue</h4><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="titreTh" value="" placeholder="Titre de la thèse"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="auteur" value="" placeholder="Auteur"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input type="text" name="etablissement_université" value="" placeholder="Etablissement/ Université"></div><div class="field-agileinfo-spc form-w3-agile-text1"><input id="dateS" name="souten" type="text" placeholder="Date de soutenance" value="" onfocus="this.value = "";" onblur="if (this.value == "") {this.value = "mm/dd/yyyy";}" required=""></div>'
    document.getElementById('ajouter_une_these').appendChild(eq);
}


//eq.innerHTML = "'Titre Complet de la publication : ' + info[0].value + ' <br> ' + ' Auteurs : ' + info[1] + ' <br> ' + ' Nom complet du périodique scientifique : ' + info[2] + ' <br> ' + 'Volume, issus, pages et année : ' + info[3] + ' <br> ' + ' Thématique : ' + info[4] + ' <br> ' + ' Lien web : ' + ' <a> ' + info[5] + ' </a> '";